import { Inter } from 'next/font/google';
import './globals.css';

// Correcto: Uso de la fuente 'Inter' desde Google Fonts
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} py-20`}>
        <h2 className="text-4xl text-center">Rick and Morty</h2>
        {children}
      </body>
    </html>
  );
}
